services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    environment:
      - PORT=5000
      - FLASK_DEBUG=false
    expose:
      - "5000"
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

