services:
  # Frontend - Static Site
  - type: web
    name: resdaddy-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend - Web Service
  - type: web
    name: resdaddy-backend
    env: python
    rootDir: backend
    buildCommand: pip install flask gunicorn python-dotenv flask-cors PyPDF2 python-docx fpdf openai
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: OPENROUTER_API_KEY
        value: ""
